process.loadEnvFile();

export const {
  APP_ORIGIN,
  PORT = 3000,
  NODE_ENV = 'development',
  DATABASE_URL,
  JWT_SECRET,
  JWT_SECRET_ACCESS,
  JWT_SECRET_REFRESH,
  NODEMAILER_USER,
  NODEMAILER_PASS,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
  MP_ACCESS_TOKEN,
  PUBLIC_API_URL,
  PUBLIC_FRONTEND_URL
} = process.env;
